const ActionTypes = {
  GET_COMPETITION_REQUEST: 'GET_COMPETITION_FAILURE',
  GET_COMPETITION_SUCCESS: 'GET_COMPETITION_SUCCESS',
  GET_COMPETITION_FAILURE: 'GET_COMPETITION_FAILURE',
};

export { ActionTypes };